# Generated by Django 3.2.12 on 2022-03-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('roll', models.IntegerField()),
                ('year', models.CharField(max_length=50)),
                ('createdTime', models.CharField(max_length=50)),
                ('createdDate', models.CharField(max_length=50)),
                ('reason', models.TextField()),
            ],
        ),
    ]
